# -*- coding: utf-8 -*-
"""asingh101_hw2_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r13hYHleopCKIOYtYsW9bAhIR4a7M-4k
"""

#!/usr/bin/env python3
"""
Chain-of-Thought Prompting with OpenAI API
Based on Wei et al. (2023)
"""

import os
from openai import OpenAI

# Initialize OpenAI client
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

# Few-shot chain-of-thought prompt from Wei et al. (2023) Table 20
# Math word problems with chain-of-thought reasoning
messages = [
    {
        "role": "user",
        "content": "Q: There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?\nA: There are 15 trees originally. Then there were 21 trees after some more were planted. So there must have been 21 - 15 = 6. The answer is 6."
    },
    {
        "role": "user",
        "content": "Q: If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?\nA: There are originally 3 cars. 2 more cars arrive. 3 + 2 = 5. The answer is 5."
    },
    {
        "role": "user",
        "content": "Q: Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?\nA: Originally, Leah had 32 chocolates. Her sister had 42. So in total they had 32 + 42 = 74. After eating 35, they had 74 - 35 = 39. The answer is 39."
    },
    {
        "role": "user",
        "content": "Q: Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?\nA:"
    }
]

# Make API call
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=messages,
    temperature=0,
    max_tokens=150
)

# Print the response
print("Chain-of-Thought Response:")
print(response.choices[0].message.content)
