# -*- coding: utf-8 -*-
"""asingh101_hw3_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoLRF8SrZHZDuDUFNG-acpasevJko2Zq
"""

import os
import requests
from openai import OpenAI

# Initialize OpenAI client
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

# Few-shot training examples (downloaded via curl)
training_examples = """
"userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"

"userId": 1,
  "id": 2,
  "title": "qui est esse",
  "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"

"userId": 1,
  "id": 3,
  "title": "ea molestias quasi exercitationem repellat qui ipsa sit aut",
  "body": "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut"

"""

# Pull new data from API
response = requests.get('https://jsonplaceholder.typicode.com/posts/5')
new_post = response.json()

# Create few-shot prompt with new data
prompt = f"""{training_examples}

Now, please summarize this new post in the same style:

Post Title: "{new_post['title']}"
Post Body: "{new_post['body']}"
Summary:"""

# Send to OpenAI API
chat_response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are a helpful assistant that summarizes posts following the given examples."},
        {"role": "user", "content": prompt}
    ],
    temperature=0.7,
    max_tokens=150
)

# Print the results
print("=" * 60)
print("NEW POST FROM API:")
print("=" * 60)
print(f"Title: {new_post['title']}")
print(f"\nBody: {new_post['body']}")
print("\n" + "=" * 60)
print("AI-GENERATED SUMMARY:")
print("=" * 60)
print(chat_response.choices[0].message.content)
print("=" * 60)